### ISSUE TITLE
Increase number of lints.

### ISSUE THREAD

**Issue by omni-viral** [amethyst/amethyst#1115]
I ended up with this list of lints for the rendy.
I think it would be useful for amethyst to add those.

```
#![forbid(overflowing_literals)]
#![deny(missing_copy_implementations)]
#![deny(missing_debug_implementations)]
#![deny(missing_docs)]
#![deny(intra_doc_link_resolution_failure)]
#![deny(path_statements)]
#![deny(trivial_bounds)]
#![deny(type_alias_bounds)]
#![deny(unconditional_recursion)]
#![deny(unions_with_drop_fields)]
#![deny(while_true)]
#![deny(unused)]
#![deny(bad_style)]
#![deny(future_incompatible)]
#![warn(rust_2018_compatibility)]
#![warn(rust_2018_idioms)]
```

**Comment by Rhuagh** [comment]
s/deny/warn/ and in CI: -D warnings

**Comment by omni-viral** [comment]
Wouldn't it break build if some dependency will start producing warning?

**Comment by torkleyy** [comment]
Yes, but that's how we catch it early. The deny attrubute breaks backwards compatibility, disallowing warnings only our CI.

**Comment by omni-viral** [comment]
I don't get it. How it breaks backward compatibility?

**Comment by jojolepro** [comment]
When rust update and there is deprecation warnings for example. There is also dependencies sometimes creating patch versions with warnings.

**Comment by omni-viral** [comment]
@jojolepro And here you should see CI failed according to @torkleyy .

**Comment by TimonPost** [comment]
I did those lints for laminar:

#![cfg_attr(feature = "cargo-clippy", deny(needless_return))]
#![warn(missing_docs)]
#[deny(
trivial_casts,
trivial_numeric_casts,
unused_extern_crates,
unused_import_braces,
unused_qualifications,
unused_results,
unused_imports
)]

You can also have lints only for Travis build. Not sure how to do that yet. So then you can have local freedom while you want to make a PR you'll have to provide docs for example.

**Comment by jojolepro** [comment]
@omni-viral no, I mean once the amethyst lib is released. For example, I'm sure amethyst 0.7 or 0.8 have compilation warnings that weren't there when we released due to dependencies update and rust updates. Imagine people that would be using those, and all of the sudden the library just stops compiling and they are forced to migrate to a new amethyst version?

**Comment by omni-viral** [comment]
@jojolepro Sorry, I can't follow. If we deny stuff and build successfully there is no way it can start failing. New warnings will still be, well, warnings.

On the other hand if we have warning as errors on CI and some dependency start emit warning because of new compiler then we will have to go there and fix it before being able to merge PRs

**Comment by omni-viral** [comment]
@TimonPost multiple `unused_*` lints can all be controlled with `unused` group.

**Comment by omni-viral** [comment]
BTW. It sometimes makes sense to leave warnings not fixed to address them later.
For example rendy build emits plenty of warnings about unnecessary `unsafe` because `hal`'s methods still "safe".

**Comment by jojolepro** [comment]
If you have a crate A that depends on B, and B depends on C: "0.1", when you build A, you also build B. Now the question is, if C updates a minor version, or rust updates and starts throwing warnings (which already happened), will the next cargo update and  cargo build fail, because B (amethyst) would have a `#deny`.

Or, does it uses the Cargo.lock of B without updating it, and it also completely ignores the lints?

We had that issue with error_chain and amethyst_renderer iirc. Rust updated and it started making warnings because of weird deprecated documentation derives. Because of the deny, we got people that were unable to compile after a cargo update.

https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md

Now, considering you manually listed the ones you want to deny, I guess it can be fine.

**Comment by jojolepro** [comment]
:+1:

**Comment by jojolepro** [comment]
hmmm sorry about that ^^
I meant to cancel the comment and put the :+1: on your comment :D

**Comment by LucioFranco** [comment]
@omni-viral Thank you for the list, when I was working on rendy they were helpful.

I am curious to hear why `deny` might be better than `warn`? I find that they both achieve the same goal in the end and that is that these items don't go onto master but `warn` provides a smoother experience. I find it lowers the barrier of entry for new contributors and it enables quick iteration.

**Comment by omni-viral** [comment]
@LucioFranco when you develop big feature `deny` forces you to keep code clean. Fixing all warnings in 5kloc PR after CI reports failure could be tedious and could end up stalling PR.

**Comment by LucioFranco** [comment]
Right, so how I see it, its either we spend that upfront cost (that we already pay by having such a strict compiler) in the design phase of the PR or in the clean-up phase. I personally am for the cost during clean up, as I would prefer to iterate and validate my code then go through and clean it up. I also think the PR stalling is better than the design phase taking too long.

The other thing to note, is that if you want to work with these as errors can you not just use `-D warnings` locally?

**Comment by Rhuagh** [comment]
Having them as warn will create warnings, you should never flag a PR as complete until you've fixed ALL warnings. While `#[deny(..)]` make it so you can't test compile your new changes mid change without a lot of annoyance.

**Comment by omni-viral** [comment]
@LucioFranco @Rhuagh the only use cases where warnings won't work is when you have some warnings that you can't address right now but still want to merge PR.
For example I have "unused" unsafe blocks because gfx-hal lies about function safety.

**Comment by omni-viral** [comment]
During rapid prototyping I do s/#![deny/#![warn/g and revert it when I'm want to cleanup.

**Comment by omni-viral** [comment]
However for my use case with gfx-hal I canl add `#![allow(unused_unsafe)]` and remove it when it's time to make things right.

**Comment by LucioFranco** [comment]
> During rapid prototyping I do s/#![deny/#![warn/g and revert it when I'm want to cleanup.

@omni-viral This is kind of what I want to avoid. This should be done via CI. Meaning that when you code you leave it on `warn` and when you are ready to submit your PR you use `deny` but the `deny` is done via `-D warnings` on CI. To me, this accomplishes the same thing as you mentioned without the need to actually modify the `lib.rs`.

**Comment by fhaynes** [comment]
Closing this due to inactivity. Currently CI is set to treat warnings as errors.
