### ISSUE TITLE
Cannot build amethyst_locale 0.13: does not implement a trait

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [amethyst/amethyst#1960]
Just started a new project via `cargo new --bin`. Added Amethyst 0.13, the latest version to my dependencies:

```
[dependencies]
amethyst = {version="0.12.0", features=["vulkan"]}
```

Compiling resulted in an error:

```
>cargo build -j 1
   Compiling amethyst_locale v0.7.0
error[E0277]: the trait bound `unic_langid_impl::LanguageIdentifier: std::convert::From<unic_langid_impl::LanguageIdentifier>` is not satisfied
  --> C:\Users\Col\.cargo\registry\src\github.com-1ecc6299db9ec823\amethyst_locale-0.7.0\src\lib.rs:37:26
   |
37 |         let mut bundle = FluentBundle::new(&[lang_en]);
   |                          ^^^^^^^^^^^^^^^^^ the trait `std::convert::From<unic_langid_impl::LanguageIdentifier>` is not implemented for `unic_langid_impl::LanguageIdentifier`
   |
   = note: required because of the requirements on the impl of `std::convert::Into<unic_langid_impl::LanguageIdentifier>` for `unic_langid_impl::LanguageIdentifier`
   = note: required by `fluent_bundle::bundle::FluentBundle::<R>::new`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `amethyst_locale`.

To learn more, run the command again with --verbose.
```

Running rust v1.38.0 (latest, ran rustup update before building) on Windows 10.

**Comment by azriel91** [comment]
Shall be fixed by #1959.

**Comment by JPMoresmau** [comment]
Add the same issue, it was solved by building from git. I ran `cargo update -p amethyst` and then modified my cargo.toml
```
[dependencies.amethyst]
version = "0.13"
git = "https://github.com/amethyst/amethyst.git"
features = ["vulkan"]
```
Since I struggled a little bit, maybe these notes can be useful to somebody...

**Comment by ColonelThirtyTwo** [comment]
@JPMoresmau Yeah, cuz #1959 is merged. I hope there will be a hotfix release, since having your most recent version of your crate not buildable is sloppy.

**Comment by mrhatman** [comment]
I second doing hotfix

**Comment by distransient** [comment]
Patch version 0.13.1 is being built and published for this. Please comment to reopen if #1959 does not fix this issue.
