### ISSUE TITLE
[BUG] Build fails with broken dependency chain rendy -> gfx-backend-metal -> objc

### ISSUE THREAD

**Issue by bonsairobo** [amethyst/amethyst#2011]
## Description

`amethyst_rendy` dependency fails to build with the "metal" feature, because it depends on objc v0.2.7, which recently changed undefined behavior (for future rust versions) into a compile error. 

Relevant issues:

https://github.com/SSheldon/rust-objc/issues/62
https://github.com/SSheldon/rust-objc/issues/86

Relevant PR:

https://github.com/gfx-rs/gfx/pull/3050

Relevant commit:

https://github.com/SSheldon/rust-objc/commit/735816219676ad2b569163315cd23b002d1492ea

The fallout is that anyone who `cargo update` to this version will not be able to compile the `metal` v0.15.0 crate.

My workaround is to put the line

`objc = "=0.2.6"`

in my Cargo.toml.

## Reproduction Steps

1. Checkout any version of amethyst that supports rendy (including master at the time of posting).
2. `cargo update`
3. `cargo run --example rendy --features="metal animation gltf"`

## What You Expected to Happen

A successful build.

## What Actually Happened

A failing build.

## Screenshots and Logs

```
error[E0282]: type annotations needed
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/metal-0.15.0/src/device.rs:1533:21
     |
1533 |                     msg_send![err, release];
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^ consider giving `result` a type
     |
     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
...etc...
```

## Your Environment

1. Mac OS 10.14.6
3. Amethyst v0.13.2

**Comment by SSheldon** [comment]
Oof, sorry y'all didn't get any heads up before this happened, I didn't find this dependency ahead of time. Getting to metal 0.16 or greater will fix the issue, but it looks like to that you'll need gfx-backend-metal at 0.3 which means rendy at 0.4 in amethyst_rendy.

Fortunately, it looks like someone is already working on that in #1908!

**Comment by andrewgrz** [comment]
> My workaround is to put the line
>
> objc = "=0.2.6"

Thanks for providing the work around! Worked for me on:

    Mac OS 10.14.6
    Amethyst v0.13.2

as well.

**Comment by distransient** [comment]
Fixed with #1908 I think

**Comment by benjaminbours** [comment]
I still got the issue, I'm on the same spec
```
Mac OS 10.14.6
Amethyst v0.13
```
I'm just following the pong tutorial and I couldn't build it. :S But I was able to build the exemple from this repository.

Here is my Cargo.toml
```
[package]
name = "pong"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies.amethyst]
version = "0.13"
features = ["metal"]
```

It seems #1908 did not fixed it.

But the work around fixed it, so thanks for that 👍

**Comment by gamecubate** [comment]
Why would you close this issue when it's still pertinent for me. Spent 30 minutes trying to compile for Mac OS when I stumbled upon this. Documentation could use an update.

**Comment by distransient** [comment]
It's fixed on master. We keep open issues so we can keep track of what we need to fix. Normally CI will actually automatically close an issue if a PR with the text "fixes #XXX" is merged, but the relevant PR for this was not marked, so I closed it manually. If this is still broken on master, let me know and I will reopen it.

**Comment by SSheldon** [comment]
And judging by the 0.14 milestone, it looks like the new version isn't too far off from being published! https://github.com/amethyst/amethyst/milestone/11

**Comment by gamecubate** [comment]
It works on master. Thanks.

**Comment by paul-nelson-baker** [comment]
Unfortunately this seems to have regressed. To reproduce, ensure you're using the most recent amethyst and create a new project.
```bash
$ amethyst update
> No new versions found.
$ amethyst --version
> Amethyst CLI 0.9.1
$ amethyst new my-pong
```

Neither amethyst `0.12.0` NOR `master` (current commit: d647450) will compile with metal as the backend:

```toml
[dependencies]
amethyst = "0.12.0"
```
```toml
[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "master" }
```

When the objc dependency is manually added, `master` **_will not_** work but `0.12.0` **_does_**.
```toml
[dependencies]
amethyst = "0.12.0"
objc = "=0.2.6"
```

**Comment by louisgjohnson** [comment]
Having this issue as well..

**Comment by mentero** [comment]
I can confirm. I had to add 

```toml
quote = "=1.0.2"
objc = "=0.2.6"
```

in order to run an empty project. It worked, but with a warning about unused imports

```
warning: unused imports: `ReadExpect`, `Resources`, `SystemData`
 --> src/main.rs:3:20
```
