### ISSUE TITLE
[BUG] Black screen on linux for examples with glTF

### ISSUE THREAD

**Issue by othelarian** [amethyst/amethyst#2045]
# Tasks
- Figure out why sometimes the asset doesn't load to completion (or figure out if it is just slow)

## Description

When running examples "rendy" and "gltf", the window stay black and nothing append.

## Reproduction Steps

1. execute `cargo run --example gltf --features "vulkan animation gltf"`
OR
1. execute  `cargo run --example rendy --features "vulkan animation gltf"`

## What You Expected to Happen

A window with the correct render.

## What Actually Happened

A black window.

## Screenshots and Logs

Log for "rendy" example:

>Create spheres
Create lights
Loading complete.

Log for "gltf" example: https://gist.github.com/othelarian/c3080af2772f6a0ed823836ea9138813

## Your Environment

Ubuntu 18.04.3 LTS
Intel(R) Xeon(R) CPU E3-1245 v3 @ 3.40GHz
Intel Corporation Xeon E3-1200 v3 Processor Integrated Graphics Controller
mesa-va-drivers 19.0.8-0
mesa-vulkan-drivers 19.0.8-0
amethyst versions:

* master commit 8517be98c28d8f9469db2070dea54e7da15b7919
* 0.13.2 commit 9a51fa3f880cb5ed6b54d63abfad8a9876aa7810

## Additional Context

All other examples work well, with 60fps.

**Comment by Hugal31** [comment]
You are missing `--` before `--features`. If it doesn work, try to move `--features "vulkan animation gltf"` before `--example`, like this:
`cargo run --features "vulkan animation gltf" --example gltf`
`cargo run --features "vulkan animation gltf" --example rendy `
to make sure `--features` is not taken as an argument to the example program.

If it still doesn't work please post the log output here.

**Comment by 0x6273** [comment]
Nov 21, 2019, 13:54 by notifications@github.com:
You are missing -- before --features. If it doesn work, try to move --features "vulkan animation gltf" before --example, like this:
 cargo run --features "vulkan animation gltf" --example gltf
 cargo run --features "vulkan animation gltf" --example rendy 
 to make sure --features is not taken as an argument to the example program.
If it still doesn't work please post the log output here.

**Comment by othelarian** [comment]
I corrected the commands, thanks for noticing. To be sure, I inversed the args order, and it changed nothing. I also cloned again without executing git-lfs, and I had an explicit error in the log about the assets, so gltf prefabs seems loaded.

**Comment by jojolepro** [comment]
The gltf example takes a while to load if you are not running with the --release flag. Try with it and keep us updated if the issue continues using the latest code on github. Thanks!

**Comment by TheRealBluesun** [comment]
I receive a black screen on the pong example, which I've run with the following:

`cargo run --example pong_tutorial_01 --features "vulkan"`

However I'm able to run the gltf example.  Any ideas?

```
5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 19.3 Tricia
```

NVIDIA drivers 440.82-0ubuntu0~0.18.04.1

**Comment by troykinsella** [comment]
Confirming this is still an issue on amethyst `0.15.3` with certain hardware/configurations(?) but not others.

## Common in both cases

* Output:
```
cargo run --example gltf --features "vulkan,animation,gltf"
    Finished dev [unoptimized + debuginfo] target(s) in 0.65s
     Running `target/debug/examples/gltf`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.15.3
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: b6d0b6acafce64e3a97479101a6e920bbc5c1bac
[INFO][amethyst::app] Rustc version: 1.46.0 Stable
[INFO][amethyst::app] Rustc git commit: 04488afe34512aa4c33566eb16d8c912a3ae04f9
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
[DEBUG][amethyst_assets::loader] "PREFAB": Loading asset "mesh/puffy.gltf" with format "GLTFScene" from source "[default source]" (handle id: Handle { id: 0 })
[DEBUG][amethyst_assets::storage] "PREFAB": Asset "prefab/puffy_scene.ron" (handle id: Handle { id: 0 }) is not complete, readding to queue
[DEBUG][amethyst_gltf::format] Loading GLTF scene 'mesh/puffy.gltf'
[DEBUG][amethyst_assets::storage] "PREFAB": Asset "prefab/puffy_scene.ron" (handle id: Handle { id: 0 }) is not complete, readding to queue
...
[DEBUG][amethyst_assets::storage] "PREFAB": Asset "mesh/puffy.gltf" (handle id: Handle { id: 0 }) has been loaded successfully
[DEBUG][amethyst_assets::storage] "PREFAB": Asset "prefab/puffy_scene.ron" (handle id: Handle { id: 0 }) has been loaded successfully
...
```

* Ubuntu 20.04.1 LTS
* `mesa-va-drivers`: `20.0.4-2ubuntu1`
* `mesa-vulkan-drivers`: `20.0.4-2ubuntu1`

## Broken / black-screen case

* Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
* Intel Corporation HD Graphics 5500
* Also tried with `--release` and waited a good long while -> same result

## Working case

* AMD Ryzen 7 2700X Eight-Core Processor
* Radeon RX 5600 / 5700 / XT

**Comment by FlyingRatBull** [comment]
I ran into this bug today with the following HW:
* AMD Ryzen 7 3800 XT Eight-Core Processor
* nVidia GTX 1070 (nVidia prop. drivers)
* release/debug

I also debugged it and interestingly enough `RonFormat::import_simple` ran through, but it would not be handled as loaded:
```
[DEBUG][amethyst_assets::storage] "PREFAB": Asset "prefab/puffy_scene.ron" (handle id: Handle { id: 0 }) is not complete, readding to queue
```
With hints as to which direction to look, I could spend some time debugging it further.
